### ISSUE TITLE
Check fails on test_stream_bad_cmd but stream_to_command didn't change

### ISSUE THREAD

**Issue by johnkeates** [statsite/statsite#246]
There seems to be some sort of issue with the unit tests, when check executes them it fails on test_streaming.c line 125, which is where stream_to_command is called with a bogus stream command. The idea of course being that the code should know that a bad stream command should return zero. Either the test is bad, or the stream_to_command implementation is bad, but I haven't actually seen any changes to either bits of code beween a passing revision and a broken revision.

It would be great if someone could look at this besides me, because apparently staring the same code a lot doesn't help with finding the problem.

**Comment by johnkeates** [comment]
It appears lines 86 and 87 were swapped in streaming.c a bit ago, which broke the test. Fixed it in my next monster-merge.

**Comment by dpkp** [comment]
It seemed to me that it was the change to WNOHANG not the ordering that was
the problem. waitforpid should block when called wo WNOHANG, shouldn't it?
In which case, why do you need to sleep beforehand?

**Comment by johnkeates** [comment]
No, that's just something I did wrong ;-) WNOHANG seems to be a constant for 0 anyway (as was defined in an older revision), the problem is the do-while loop. The thing is that the OS needs a tiny amount of time (probably something close to the time slicing quantum) before waitpid() actually has something useful to do. Since the first time it runs immediately (as do-while does) and the OS probably hasn't had time yet to update process information (or maybe the fork or thread for the pid hasn't even had a multitask slice yet) it would immediately continue (and fail). That microsleep makes sure that there is at least a minimal amount of time to run, and then actually loops until the pid status changes. It's probably also why sometimes the check target fails and other times it doesn't (hence the Travis-CI re-runs), it's a race condition on the first run. On later loop runs, the microsleep most likely helps with not sucking up CPU time, which is why the sleep is inside the loop and not outside. I'm not sure why it was moved below the if-statement, maybe it was a refactoring error by someone.

**Comment by dpkp** [comment]
Strange...
```
> grep WNOHANG /usr/include/x86_64-linux-gnu/bits/waitflags.h
#define	WNOHANG		1	/* Don't block waiting.  */
```

**Comment by johnkeates** [comment]
Double-strange, the diff shows 0. One manpage shows 0 too (on die.net), but the local man says 1, and printing WNOHANG prints 1 too. I'm confused. On the other hand, this works, and was in a 2015 revision as well. The first waitpid don't want to block waiting, but the second one does in streaming.c. I changed it to WNOHANG and it still builds/runs successfully. I suppose the flag actually doesn't matter in this use case since it's in a loop anyway.

**Comment by johnkeates** [comment]
Looks like I checked the wrong reference and the local man / code was right and my diff was bad (and die.net, well, I must have looked at the wrong page). Regardless, I'll change the flag, the test will still run, the code will still be correct and the small sleep before checking with waitpid() will still be in the right place. All is well.

**Comment by dpkp** [comment]
the problem is/was that `waitpid(pid, &status, WNOHANG)` can return -1 when the pid is not ready.  (If it is called in normal blocking mode, it just blocks). But more important, when in non-blocking mode you are not actually getting anything useful in &status -- it's just going to stay at whatever value it had prior to the call. In this case, status is initialized to 0 (success). So what I believe was happening was that waitpid returned -1 instead of blocking, this caused the `break` statement to  exit the do / while loop, and then the outer function returns `WEXITSTATUS(status);` which, because waitpid did not block to update the value, was still just at the intialized value of 0.

The test that failed was the only test that requires a non-0 return value (passes a non-existent command):
fail_unless(res != 0);

Which is why I dont think the ordering has much to do with solving the test failure you noticed.
