### ISSUE TITLE
log_facility streaming logs to syslog

### ISSUE THREAD

**Issue by pantocrator27** [statsite/statsite#255]
It appears that a lot of people are running statsite inside of a docker container.  With that and notions of 12 factor app principles such as:

> A twelve-factor app never concerns itself with routing or storage of its output stream. It should not attempt to write to or manage logfiles. Instead, each running process writes its event stream, unbuffered, to stdout. During local development, the developer will view this stream in the foreground of their terminal to observe the app’s behavior.

would it be worth evaluating whether or not to allow an option to stream logs to stdout.  This behavior would also be in keeping with how a lot of the other Hashicorp tools which rely on statsite handle logging behavior?

**Comment by johnkeates** [comment]
I'm not sure how this would be implemented since there are multiple streams. I'm not running statsite in a docker container so I don't know how others are doing it, but I imagine specifying a socket to write to and using that is the input for whatever you use to consume the stream might work just as well.

At the same time, the information log is already going to stdout, so nothing to change there.

**Comment by pantocrator27** [comment]
@johnkeates would it be worthwhile then to consider an option to disable routing to syslog?

**Comment by johnkeates** [comment]
Sidenote: by specifying an unused facility, syslog won't record anything. 12factor is for maintaining logfiles outside of syslog, but that can be avoided with foreground mode.
